name: reviewdog
on:
  workflow_dispatch:
    inputs:
      glob_pattern:
        required: false
        description: "Glob pattern of the files to lint"
        default: "interfacemaster/*.py"
jobs:
  pylint:
    name: runner / pylint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dciborow/action-pylint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          level: warning
          glob_pattern: ${{ inputs.glob_pattern }}
